import { MessageCircle, Mail, Globe, Instagram, Facebook } from "lucide-react";
import type { Conversation, CallLog, ChannelConfig } from "./types";

export const conversations: Conversation[] = [
  {
    id: 1,
    contact: {
      id: 1,
      firstName: "Jay",
      lastName: "Kanani",
      email: "jay@kanani.com",
      phone: "1234567890",
      company: "Kanani",
      lifecycleStage: "New Lead",
      tags: ["New Lead"],
      avatar: "JK",
      channel: "whatsapp",
    },
    lastMessage: {
      id: 1,
      conversationId: 1,
      type: "reply",
      text: "Yo, when is the meeting?",
      author: "Jay Kanani",
      initials: "JK",
      time: "9:59 AM",
      status: "sent",
      direction: "incoming",
      channel: "whatsapp",
    },
    time: "9:59 AM",
    unreadCount: 0,
    tag: "New Lead",
    channel: "whatsapp",
    direction: "incoming",
  },
  {
    id: 2,
    contact: {
      id: 2,
      firstName: "Sarah",
      lastName: "Miller",
      email: "sarah@miller.com",
      phone: "0987654321",
      company: "Miller",
      lifecycleStage: "Hot Lead",
      tags: ["Hot Lead"],
      avatar: "SM",
      channel: "gmail",
    },
    lastMessage: {
      id: 2,
      conversationId: 2,
      type: "reply",
      text: "Thanks for the info!",
      author: "Sarah Miller",
      initials: "SM",
      time: "9:45 AM",
      status: "sent",
      direction: "outgoing",
      channel: "gmail",
    },
    time: "9:45 AM",
    unreadCount: 2,
    tag: "Hot Lead",
    channel: "gmail",
    direction: "outgoing",
  },
  {
    id: 3,
    contact: {
      id: 3,
      firstName: "Mike",
      lastName: "Johnson",
      email: "mike@johnson.com",
      phone: "1122334455",
      company: "Johnson",
      lifecycleStage: "Customer",
      tags: ["Customer"],
      avatar: "MJ",
      channel: "email",
    },
    lastMessage: {
      id: 3,
      conversationId: 3,
      type: "reply",
      text: "When can we schedule a call?",
      author: "Mike Johnson",
      initials: "MJ",
      time: "9:30 AM",
      status: "sent",
      direction: "incoming",
      channel: "email",
    },
    time: "9:30 AM",
    unreadCount: 0,
    tag: "Customer",
    channel: "email",
    direction: "incoming",
  },
  {
    id: 4,
    contact: {
      id: 4,
      firstName: "Priya",
      lastName: "Sharma",
      email: "priya@sharma.com",
      phone: "1122334455",
      company: "Sharma",
      lifecycleStage: "New Lead",
      tags: ["New Lead"],
      avatar: "PS",
      channel: "instagram",
    },
    lastMessage: {
      id: 4,
      conversationId: 4,
      type: "reply",
      text: "I saw your post, interested!",
      author: "Priya Sharma",
      initials: "PS",
      time: "8:50 AM",
      status: "sent",
      direction: "incoming",
      channel: "instagram",
    },
    time: "8:50 AM",
    unreadCount: 3,
    tag: "New Lead",
    channel: "instagram",
    direction: "incoming",
  },
  {
    id: 5,
    contact: {
      id: 5,
      firstName: "Tom",
      lastName: "Bradley",
      email: "tom@bradley.com",
      phone: "1122334455",
      company: "Bradley",
      lifecycleStage: "Customer",
      tags: ["Customer"],
      avatar: "TB",
      channel: "messenger",
    },
    lastMessage: {
      id: 5,
      conversationId: 5,
      type: "reply",
      text: "Please send the invoice again.",
      author: "Tom Bradley",
      initials: "TB",
      time: "Yesterday",
      status: "sent",
      direction: "outgoing",
      channel: "messenger",
    },
    time: "Yesterday",
    unreadCount: 0,
    tag: "Customer",
    channel: "messenger",
    direction: "outgoing",
  },
  {
    id: 6,
    contact: {
      id: 6,
      firstName: "Lena",
      lastName: "Fischer",
      email: "lena@fischer.com",
      phone: "1122334455",
      company: "Fischer",
      lifecycleStage: "Hot Lead",
      tags: ["Hot Lead"],
      avatar: "LF",
      channel: "whatsapp",
    },
    lastMessage: {
      id: 6,
      conversationId: 6,
      type: "reply",
      text: "Got your message, will reply soon",
      author: "Lena Fischer",
      initials: "LF",
      time: "Yesterday",
      status: "sent",
      direction: "incoming",
      channel: "whatsapp",
    },
    time: "Yesterday",
    unreadCount: 1,
    tag: "Hot Lead",
    channel: "whatsapp",
  },
];

export const channelConfig: Record<string, ChannelConfig> = {
  whatsapp: {
    icon: "https://cdn.simpleicons.org/whatsapp",
    bg: "bg-green-500",
    label: "WhatsApp",
  },
  instagram: {
    icon: "https://cdn.simpleicons.org/instagram",
    bg: "bg-pink-500",
    label: "Instagram",
  },
  messenger: {
    icon: "https://cdn.simpleicons.org/messenger",
    bg: "bg-blue-600",
    label: "Messenger",
  },
  gmail: {
    icon: "https://cdn.simpleicons.org/gmail",
    bg: "bg-red-500",
    label: "Gmail",
  },
  email: {
    icon: "https://cdn.simpleicons.org/maildotru",
    bg: "bg-blue-500",
    label: "Email",
  },
  websitechat: {
    icon: "https://cdn.simpleicons.org/googlechat",
    bg: "bg-purple-500",
    label: "Website Chat",
  },
};

export const teamMembers = [
  { id: "u1", name: "Alice Johnson", initials: "AJ", online: true },
  { id: "u2", name: "Bob Smith", initials: "BS", online: true },
  { id: "u3", name: "Carol White", initials: "CW", online: false },
  { id: "u4", name: "David Lee", initials: "DL", online: true },
  { id: "u5", name: "Eva Martinez", initials: "EM", online: false },
];

export const teams = [
  { id: "t1", name: "Sales Team", color: "bg-blue-500" },
  { id: "t2", name: "Support Team", color: "bg-purple-500" },
  { id: "t3", name: "Tech Team", color: "bg-orange-500" },
];

export const callLogs: CallLog[] = [
  {
    id: 1,
    contact: {
      id: 1,
      firstName: "Jay",
      lastName: "Kanani",
      email: "jay@kanani.com",
      phone: "1234567890",
      company: "Kanani",
      lifecycleStage: "New Lead",
      tags: ["New Lead"],
      avatar: "JK",
      channel: "whatsapp",
    },
    direction: "incoming",
    duration: "3m 12s",
    time: "9:59 AM",
    tag: "New Lead",
  },
  {
    id: 2,
    contact: {
      id: 2,
      firstName: "Sarah",
      lastName: "Miller",
      email: "sarah@miller.com",
      phone: "0987654321",
      company: "Miller",
      lifecycleStage: "Hot Lead",
      tags: ["Hot Lead"],
      avatar: "SM",
      channel: "gmail",
    },
    direction: "outgoing",
    duration: "1m 45s",
    time: "9:45 AM",
    tag: "Hot Lead",
  },
  {
    id: 3,
    contact: {
      id: 3,
      firstName: "Mike",
      lastName: "Johnson",
      email: "mike@johnson.com",
      phone: "1122334455",
      company: "Johnson",
      lifecycleStage: "Customer",
      tags: ["Customer"],
      avatar: "MJ",
      channel: "email",
    },
    direction: "missed",
    duration: "",
    time: "9:30 AM",
    tag: "Customer",
  },
  {
    id: 4,
    contact: {
      id: 4,
      firstName: "Jay",
      lastName: "Kanani",
      email: "jay@kanani.com",
      phone: "1234567890",
      company: "Kanani",
      lifecycleStage: "New Lead",
      tags: ["New Lead"],
      avatar: "JK",
      channel: "whatsapp",
    },
    direction: "outgoing",
    duration: "7m 02s",
    time: "8:15 AM",
    tag: "New Lead",
  },
  {
    id: 5,
    contact: {
      id: 5,
      firstName: "Sarah",
      lastName: "Miller",
      email: "sarah@miller.com",
      phone: "0987654321",
      company: "Miller",
      lifecycleStage: "Hot Lead",
      tags: ["Hot Lead"],
      avatar: "SM",
      channel: "gmail",
    },
    direction: "incoming",
    duration: "2m 30s",
    time: "Yesterday",
    tag: "Hot Lead",
  },
];

export const subSidebarItems = [
  { label: "All", dot: "bg-gray-400", count: 2 },
  { label: "Mine", dot: "bg-blue-600", count: null },
  { label: "Unassigned", dot: "bg-gray-400", count: 1 },
];

export const lifecycleItems = [
  { label: "New Lead", bg: "bg-blue-100", dot: "bg-blue-600" },
  { label: "Hot Lead", bg: "bg-orange-100", dot: "bg-orange-600" },
  { label: "Payment", bg: "bg-green-100", dot: "bg-green-600" },
  { label: "Customer", bg: "bg-purple-100", dot: "bg-purple-600" },
];

export const WAVEFORM_BARS = [
  10, 20, 14, 26, 12, 22, 18, 28, 10, 16, 24, 12, 20, 26, 14, 18, 22, 10, 24,
  16,
];

export const emojiCategories = [
  {
    label: "Smileys",
    emojis: [
      "😀",
      "😂",
      "😍",
      "🥰",
      "😎",
      "🤔",
      "😅",
      "😭",
      "😊",
      "😢",
      "😡",
      "🤣",
      "😴",
      "🤗",
      "😬",
      "🙄",
    ],
  },
  {
    label: "Gestures",
    emojis: [
      "👍",
      "👎",
      "👋",
      "🙏",
      "💪",
      "🤝",
      "👏",
      "✌️",
      "🤞",
      "👌",
      "🫶",
      "🫡",
    ],
  },
  {
    label: "Symbols",
    emojis: [
      "❤️",
      "🔥",
      "✅",
      "⭐",
      "🎉",
      "💯",
      "🚀",
      "💡",
      "📌",
      "📎",
      "🔗",
      "💬",
      "📧",
      "📞",
      "⚡",
      "🎯",
    ],
  },
];

export const variables = [
  {
    key: "contact.name",
    label: "Contact Name",
    description: "Full name of the contact",
    category: "Contact",
  },
  {
    key: "contact.email",
    label: "Contact Email",
    description: "Email address of the contact",
    category: "Contact",
  },
  {
    key: "contact.phone",
    label: "Contact Phone",
    description: "Phone number of the contact",
    category: "Contact",
  },
  {
    key: "contact.company",
    label: "Company",
    description: "Contact's company name",
    category: "Contact",
  },
  {
    key: "agent.name",
    label: "Agent Name",
    description: "Assigned agent's name",
    category: "Agent",
  },
  {
    key: "agent.email",
    label: "Agent Email",
    description: "Assigned agent's email",
    category: "Agent",
  },
  {
    key: "company.name",
    label: "Company Name",
    description: "Your company name",
    category: "Company",
  },
  {
    key: "conversation.id",
    label: "Conversation ID",
    description: "Unique conversation ID",
    category: "System",
  },
  {
    key: "today.date",
    label: "Today's Date",
    description: "Current date",
    category: "System",
  },
];

export const snoozeOptions = [
  { label: "30 minutes", value: "30m" },
  { label: "1 hour", value: "1h" },
  { label: "3 hours", value: "3h" },
  { label: "Tomorrow morning", value: "tomorrow" },
  { label: "Next week", value: "nextweek" },
];
