export {
  WORKFLOW_DEFAULT_NODE_COLOR as DEFAULT_NODE_COLOR,
  WORKFLOW_STEP_NODE_COLORS as STEP_NODE_COLORS,
  WORKFLOW_TRIGGER_NODE_COLOR as TRIGGER_NODE_COLOR,
  getWorkflowNodeColor,
} from "../../../config/workflowMetadata";
